app = "pokedex-abc111"
kill_signal = "SIGINT"
kill_timeout = "5s"
primary_region = "arn"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080  
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 0

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024  