name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Run E2E tests
        run: npm run test:e2e
        env:
          CYPRESS_BASE_URL: http://localhost:5000

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Fly.io
        uses: superfly/flyctl-actions@1.4
        with:
          args: 'deploy --app pokedex-abc111'
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  discord-notify:
    runs-on: ubuntu-latest
    needs: [build, test, deploy]
    if: always()
    steps:
      - name: Success Notification
        if: success()
        uses: Ilshidur/action-discord@master
        with:
          args: |
            A new version of Pokedex deployed
            to https://pokedex-abc111.fly.dev by ${{ github.actor }}
          embed: true
          embed_color: '0000FF'
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: 'GitHub'

      - name: Failure Notification
        if: failure()
        uses: Ilshidur/action-discord@master
        with:
          args: |
            Build failed
            commit https://github.com/${{ github.repository }}/commit/${{ github.sha }}
            by ${{ github.actor }} broke the build :(
          embed: true
          embed_color: 'FF0000'
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: 'GitHub'
